version: "3.3"
services:
  strapi:
    container_name: website-cms
    image: website-cms
    build: ./cms
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: $STRAPI_DB_USER
      DATABASE_PASSWORD: $STRAPI_DB_PASSWORD
    # volumes:
    #   - ./cms:/app
    ports:
      - "8008:1337"
    depends_on:
      - postgres
    command: "strapi start"

  postgres:
    image: postgres
    container_name: website-cms-db
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: $STRAPI_DB_USER
      POSTGRES_PASSWORD: $STRAPI_DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - $STRAPI_DB_DATA:/var/lib/postgresql/data
