version: "3.3"
services:
  next:
    build: ./next
    image: website-frontend
    container_name: website-frontend
    restart: unless-stopped
    ports:
      - 5004:3000
    environment:
      # DONT CHANGE HERE, CHANGE .env FILE INSIDE PROJECT
      # SINCE process.env is part of node, not the browser,
      # variables get accessed during build
      # - NEXT_PUBLIC_STRAPI_URL=<example.org>
      # - PLACEHOLDER_IMAGE_URL=<example.org>
      # - STRIPE_SECRET_KEY=<example>
      # - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=<example>
      - TZ=Europe/Madrid

  strapi:
    container_name: website-cms
    image: website-cms
    build: ./cms
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: $STRAPI_DB_USER
      DATABASE_PASSWORD: $STRAPI_DB_PASSWORD
    # volumes:
    #   - ./cms:/app
    ports:
      - "8008:1337"
    depends_on:
      - postgres
    command: "strapi start"

  postgres:
    image: postgres
    container_name: website-cms-db
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: $STRAPI_DB_USER
      POSTGRES_PASSWORD: $STRAPI_DB_PASSWORD
    # ports:
    #   - "5432:5432"
    volumes:
      - $STRAPI_DB_DATA:/var/lib/postgresql/data
