version: "3.3"
services:
  strapi:
    image: strapi/strapi
    container_name: website_cms
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: $STRAPI_DB_USER
      DATABASE_PASSWORD: $STRAPI_DB_PASSWORD
    volumes:
      - ./cms:/srv/app
    ports:
      - "1338:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: website_cms_db
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: $STRAPI_DB_USER
      POSTGRES_PASSWORD: $STRAPI_DB_PASSWORD
    volumes:
      - $STRAPI_DB_DATA:/var/lib/postgresql/data
